spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto_usei
    username: postgres
    password: 78940756
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
