
POST http://localhost:8080/certificado
Content-Type: application/json
Accept: application/json

{
  "formato": "E'\\x4d79537472696e67'",
  "version": 1,
  "fecha_modificacion": "14/09/2024",
  "Usuario_id_usuario": {
      "id_usuario": 1
    }
}

###

GET http://localhost:8080/certificado

###

GET http://localhost:8080/certificado/1



###
PUT http://localhost:8080/certificado/1
Content-Type: application/json
Accept: application/json

{
  "formato": "E'\\x4d79537472696e67'",
  "version": 2,
  "fecha_modificacion": "15/09/2024",
  "Usuario_id_usuario": {
      "id_usuario": 1
    }
}
