###
GET http://localhost:8082/estado_certificado/estado/1

###
GET http://localhost:8082/estado_certificado/archivo/6

###
GET http://localhost:8082/estado_certificado/certificados-emitidos


###
GET http://localhost:8082/estado_certificado/certificados-emitidos?anio=2023